add Home work lesson 11
ISirota/RD_Python pull request #7
Opened 2023-01-18 20:15 UTC by ISirota

add Home work lesson 11

2023-01-18 21:48 UTC, klymenok requested changes

2023-01-18 21:48 UTC, klymenok commented on dz11_part1.py
> +        func(*args, **kwargs)
add `return` here to be able to decorate functions that return some value

2023-01-18 21:48 UTC, klymenok commented on dz11_part3.py
> +except AttributeError:
You can simplify this part and don't use hardcoded values: `except Exception as e: print(f'{e}')`

2023-01-21 21:05 UTC, ISirota commented on dz11_part1.py
> +        func(*args, **kwargs)
Доброго часу. Незовсім зрозумів про який ретурн. у программі в рядку 10 є return wrap

2023-01-21 21:06 UTC, ISirota commented on dz11_part3.py
> +except AttributeError:
Дякую. Гарний вираз. Не знав.

2023-01-24 22:57 UTC, klymenok requested changes

2023-01-24 22:57 UTC, klymenok commented on dz11_part1.py
> +        func(*args, **kwargs)
Потрібно додати ще один ретурн. Мій коментар стосується рядка номер 9. `return func(*args, **kwargs)`

2023-01-24 22:57 UTC, klymenok commented on dz11_part3.py
> +print(10 * '=')
Put this print to `finally` block to make it a part of the whole `try except finally` construction

2023-01-28 09:09 UTC, ISirota commented on dz11_part3.py
> +print(10 * '=')
виконано

2023-01-29 15:01 UTC, klymenok approved these changes
Looks good!

2023-02-26 20:25 UTC, merged